Models
MaskaSaw/Hotels-project pull request #1
Opened 2021-02-02 08:00 UTC by MaskaSaw

Пулл реквест на два таска: на добавление и конфигурацию моделей, контроллеров и их методов и на удаление лишних файлов из репозитория.

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart requested changes
How can I see your database schema? How can I deploy it to my computer?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you really need this comment here? What value does it add to your code?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you really need this comment here? What value does it add to your code?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
In what circumstances will this situation be possible?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            rooms = rooms.Where(x => x.HotelId == id).ToList();
In case when several method calls are chained start each method call from a new line.
```suggestion
            rooms = rooms
                 .Where(x => x.HotelId == id)
                 .ToList();
```

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            rooms = rooms.Where(x => x.HotelId == id).ToList();
Why do you need two ToList() calls? How will it translate to DB calls?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +            return reservations.Where(x => x.UserId == userId).ToList();
Why calling ToList() twice? How will it translate to SQL queries?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Is this really needed?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Is this really needed?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Hotels.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.2" />
Why do you need SQLite?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Hotel.cs
> +            //Rooms = new HashSet<Room>();
Do not leave commented out code

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                optionsBuilder.UseSqlServer("Server=wsa-033-71;Database=HotelsDB;Trusted_Connection=True;");
Is it a good idea to commit you computer name to public repository?
Also what if I want to use the database on some other machine?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +            modelBuilder.HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS");
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                entity.Property(e => e.Id).ValueGeneratedNever();
Here and below in this file - put second and following calls on a new line.

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                    .HasConstraintName("FK__Reservati__RoomI__32E0915F");
Is it a good name? Do you really need to have named constraint?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/appsettings.json
> +    "DefaultConnection": "Server=wsa-033-71;Database=HotelsDB;Trusted_Connection=True;MultipleActiveResultSets=true"
Is it a good idea to put your computer name in public repo?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Room.cs
> +            //Reservations = new HashSet<Reservation>();
Do not leave commented out code

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +            if (id != reservation.Id)
What if I send you a reservation data, that contains wrong roomId? Or userId? Valid userId of another user?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +            _context.Reservations.Add(reservation);
Are you sure that reservation object contains valid data?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +        [HttpGet("api/Hotels/{hotelId}/[controller]")]
Are you sure this action belong to this controller?
Also why have 2 different actions for getting list of rooms? Do you really need all rooms regardless of a hotel they belong to?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            }
Please see https://docs.microsoft.com/en-us/ef/core/querying/related-data/

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            return rooms.Where(x => x.HotelId == hotelId).ToList();
Please see https://docs.microsoft.com/en-us/ef/core/querying/client-eval

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            room.Reservations = reservations.Where(x => x.RoomId == id).ToList();
Please see https://docs.microsoft.com/en-us/ef/core/querying/related-data/

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            return room;
Please see https://docs.microsoft.com/en-us/ef/core/querying/related-data/

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you need this comment?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            _context.Rooms.Add(room);
Are you sure room has valid data? What about hotelId?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            reservations = reservations.Where(x => x.RoomId == id).ToList();
Rewrite query

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            _context.Users.Add(user);
Are you sure user object has valid data?
What about passwords, are you going just store them as clear text?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
Do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            reservations = reservations.Where(x => x.UserId == id).ToList();
Rewrite

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Hotel.cs
> +#nullable disable
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +#nullable disable
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                entity.ToTable("Hotel");
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                entity.ToTable("Room");
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +                entity.ToTable("User");
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/HotelsDBContext.cs
> +        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Reservation.cs
> +#nullable disable
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Room.cs
> +#nullable disable
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/User.cs
> +#nullable disable
Why do you need this?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/User.cs
> +            //Reservations = new HashSet<Reservation>();
Do not leave commented out code

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Room.cs
> +        public int? RoomNumber { get; set; }
My hotel has room numbers like 303A or 405-2. How can I use your product for listing them?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Room.cs
> +        public int? Cost { get; set; }
Why can't I use prices like $49.99?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Room.cs
> +        public bool? Reserved { get; set; }
Why are those nullable? What is the meaning for null in this case?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/Reservation.cs
> +        public bool? ExtraTowels { get; set; }
Why all those fields are nullable? Does it make sense to have reservation with only Id filled?

2021-02-02 17:51 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/User.cs
> +        public bool? IsAdmin { get; set; }
What null value means here?

2021-02-02 17:52 UTC, andrei-kruhliakou-itechart commented
> Пулл реквест на два таска: на добавление и конфигурацию моделей, контроллеров и их методов и на удаление лишних файлов из репозитория.

English please!

2021-02-04 09:20 UTC, MaskaSaw commented
Tried to fix most of issues; all connected with data validation will be part of one of the next tasks.

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart requested changes

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
What does this code do exactly? Why the hotel might be missing? Is NotFound proper result in this case?
Same question for all controllers

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +
What about rooms with reservations?
Also are you sure you want to actually delete data from database? Don't you want to keep history of reservations?
Same question for other controllers

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        [HttpGet("api/User/{userId}/Reservations")]
Does it really belong here? Also will this route work at all?

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        public async Task<ActionResult<IEnumerable<Reservation>>> GetReservations()
What is the use case for getting ALL reservations regardless of hotel or user? 
In general you should not allow API client to get ALL the records from database without limits for any table that can potentially hold a reasonably big number of rows.

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            room.Reservations =  await _context.Reservations.Where(x => x.RoomId == id).ToListAsync();
Every subsequent method call should be on a new line

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            var reservations = await _context.Reservations.Where(x => x.RoomId == id).ToListAsync();
Every subsequent method call should be on a new line

2021-02-04 11:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Migrations/20210204085616_InitializingMigration.Designer.cs
> +﻿// <auto-generated />
The requirements explicitly state that you should use DB first approach with Entity Framework.
It means among other things that you shouldn't use migrations.

2021-02-04 11:19 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +
I guess we should not keep rooms of deleted hotels in database, because it might provide some issues in the future. For example, it will be possible to make reservation of the room that exists in actually non-existing hotel. There are two possible ways to prevent it: add data validation for every query that will control it and change the model, providing additional field that shows is that room is actually valid or not; or we can just delete all rooms with their hotels from database. In that case, all reservations left in database will still be valid, except their connection with rooms.

2021-02-04 11:19 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
It might be missing if in exact the same time it was deleted by the other request, for example. Or am i wrong?

2021-02-04 11:33 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        [HttpGet("api/User/{userId}/Reservations")]
If we return Reservation data, action that does it should be in Reservation controller. Or am i wrong? Don't know the right answer.
This route works at all.

2021-02-04 11:37 UTC, MaskaSaw commented on hotels-backend/Hotels/Migrations/20210204085616_InitializingMigration.Designer.cs
> +﻿// <auto-generated />
I used DB first approach, made migrations just to show the database schema

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart requested changes

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
If it was modified by other request why return NotFound?

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        [HttpGet("{page}-{itemsCount}")]
Is it a good idea to make page and item count part of the resource name?

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +                .Skip((page - 1)* itemsCount)
What if I pass 2000000 as item count? or 10000000 as page?

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        [HttpGet("api/User/{userId}/Reservations")]
Judging from the URI it is part of user resource

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +                .ToListAsync();
Same question here as for reservations. Why would I need the list of all the rooms regardless of their hotels?

2021-02-04 18:58 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Migrations/20210204085616_InitializingMigration.Designer.cs
> +﻿// <auto-generated />
And what are you gonna do when schema changes?

2021-02-05 10:33 UTC, andrei-kruhliakou-itechart requested changes

2021-02-05 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        private readonly int _itemsCount = 100;
Can you think of a better name for this field that would explain its purpose?
Also why don't you use const instead of readonly?

2021-02-05 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        public async Task<ActionResult<IEnumerable<Hotel>>> GetHotels([FromQuery] int page)
It might be better UX to actually allow user specify number of items he want to get but limit the maximum number of items per page

2021-02-05 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    return Conflict(ex);
Returned status code is fine now, but why do you pass exception details? Is it OK for user to see them?

2021-02-05 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/HotelsDB/dbo/Tables/Hotel.sql
> +
Unnecessary empty lines

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart requested changes

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/HotelsDB/HotelsDB.refactorlog
> +﻿<?xml version="1.0" encoding="utf-8"?>
This file should be ignored

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Models/UserDTO.cs
> +﻿using System;
It is better to place this file in different folder (namespace) to separate DTOs from DB entities.

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            CreatePasswordHash(userDTO.Password, out passwordHash, out passwordSalt);
Several points here:
1. You can declare out parameters right in the method call
2. Using multiple out parameters is discouraged. Alternatives are tuples or separate class/struct.
3. What are the advantages of using separate method for creating hash and salt? Maybe you can change its scope? Or even consider removing it?

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        public async Task<ActionResult<IEnumerable<Hotel>>> GetHotels([FromQuery] int page, int requiredNumberOfItems)
Parameter name 'requiredNumberOfItems' is quite misleading as we actually want to set number of items **per page**.
How about 'itemsPerPage' instead, should match quite well with _maxItemsPerPage constant.

2021-02-05 18:03 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        private const int _maxItemsPerPage = 100;
Constants should be named in Pascal case, e.g. MaxItemsPerPage.

2021-02-08 08:04 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            CreatePasswordHash(userDTO.Password, out passwordHash, out passwordSalt);
I will put this in a separate class when i begin to deal with authorization

2021-02-08 08:21 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            CreatePasswordHash(userDTO.Password, out passwordHash, out passwordSalt);
Please add todo item in code and/or task in backlog for this.

2021-02-08 08:22 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-08 08:22 UTC, merged