Image processing
MaskaSaw/Hotels-project pull request #10
Opened 2021-02-24 12:49 UTC by MaskaSaw

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart requested changes
Why do you want to add those 2 random jpg files to the repo?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +        console.log(this.url);
Do not leave debug information in code

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +    public class ImageProcessor
Shouldn't the class be static as well as all method and fields are static?
Also can you think of any downsides of using static class here?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +                string filePath = $@"{folderPath}\{fileName}.{fileExtension}";
3 strings and 1 var - why?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +                var bytes = Convert.FromBase64String(base64string.Substring(base64string.IndexOf(",")+1));
Spaces around +

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +                Console.WriteLine(e.Message);
What is the purpose of writing to console? Will your application have even have it in production?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +            .Select(s => s[random.Next(s.Length)]).ToArray());
Formatting

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +            return new string(Enumerable.Repeat(chars, length)
Are you sure you will always get unique names that way?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                room.Image = ImageProcessor.GetImage(room.Image);
Are you sure this is the right way of handling images in general?
Do you see any downsides to it?
What are the alternatives?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +      reader.readAsDataURL(event.target.files[0]); // read file as data url
Why do you need to get it as DataURL? You are saving it as image file on the backend anyway.

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +  onSelectFile(event: any) { // called each time file input changes
Do not leave obvious comments

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +        private static string GetExtension(string fileName)
Is it really a file name you get here? If so then use System.IO.Path.GetExtension. If not then why the parameter name and is there a better way than string.Contains?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +            string extension = "";
Use string.Empty instead of "". Also use var as it obvious that you have string here.

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +        private static string folderPath = Path.GetFullPath(@"..\") + "Images";
Is it a reliable way of getting real folder path in web application?

2021-02-24 18:22 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +                        ";base64," + Convert.ToBase64String(imageBytes);
Formatting

2021-02-25 08:28 UTC, MaskaSaw commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +            return new string(Enumerable.Repeat(chars, length)
It should give more then 7307872110 different combinations of file names, so i think the chance of repeating is quite small.

2021-02-25 08:32 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                room.Image = ImageProcessor.GetImage(room.Image);
Alternatives are creating forms and send images as form-data, but it will require to change all my object-handling logic. I see the issues such as overloaded request, but images are used only for 2 entities and such a downside seems not so problematic.

2021-02-25 08:34 UTC, MaskaSaw commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +      reader.readAsDataURL(event.target.files[0]); // read file as data url
Because I dont know what type i should use to handle raw file data from json object, and it will require to create DTO's anyway, while this solution is working with plain text while transmitting.

2021-02-25 08:35 UTC, MaskaSaw commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +        private static string folderPath = Path.GetFullPath(@"..\") + "Images";
Do not see any issues with it, maybe i am loosing something.

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart requested changes

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +      reader.readAsDataURL(event.target.files[0]); // read file as data url
Why do you want to pass raw files in json?

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                room.Image = ImageProcessor.GetImage(room.Image);
How exactly will forms help you with GET reuqests?

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        //[Authorize (Roles ="Admin")]
Why have you commented this out?

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageProcessor.cs
> +                Console.WriteLine(e.Message);
Why using console?

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Saving/ImageProcessor.cs
> +        private static string folderPath = Path.GetFullPath(@"..\") + "Images";
Will it work in ASP.NET Core?

2021-02-25 10:33 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageProcessor.cs
> +            );
```suggestion
            return new string(
                Enumerable.Repeat(chars, imageNameLength)
                    .Select(s => s[random.Next(s.Length)])
                    .ToArray()
            );
```

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart requested changes

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.service.ts
> +    headers: new HttpHeaders({ 'Content-Type': 'multipart/form-data' })
You shouldn't use multipart/form-data for all requests, also currently you are using it only in delete for some reason.

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +
Why are you using Json serialized string here? Isn't it possible to use regular model binding directly to DTO?

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageService.cs
> +        }
Is it really unique? Can you guarantee that?

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on .gitignore
> +*jpeg
I would rather ignore the whole Images folder instead

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +            services.AddScoped<ImageService>();
Why scoped? What are the alternatives?

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageService.cs
> +        public async System.Threading.Tasks.Task<string> SaveImageAsync(IFormFile image)
Why using fully qualified name instead of importing namespace?

2021-02-25 17:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +            app.UseAuthorization();
Why did you add those whitespaces?

2021-02-26 18:09 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-26 18:09 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +    )
You could make those two operations independent. And also allow external hostings for image. Consider it for future improvements.

2021-02-26 18:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageService.cs
> +            while (File.Exists(imagePath));
You don't need this as GUID is guaranteed to be unique

2021-02-26 18:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Image Processing/ImageService.cs
>          }
What is the value in having separate function for this?
How about just $"{Guid.NewGuid()}{extension}"?

2021-02-26 18:09 UTC, merged