Free rooms filter implemented
MaskaSaw/Hotels-project pull request #17
Opened 2021-03-16 14:02 UTC by MaskaSaw

Main filtering logic implemented

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart requested changes

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            [FromQuery] DateTime? checkOut
Why don't you use an object instead on separate parameters?

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                .Where(hotel => !string.IsNullOrEmpty(city) ? hotel.City == city : true)
Prefer adding Where clauses only when you are needed them to prevent generating additional unnecessary SQL.
Also Include should go directly after the main db set and before any other operators.

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    .ToList();
Why do you need ToList here? What does it do actually?

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.ts
> +  minDate = new Date(2021,1,1);
Why don't you use object instead of separate parameters?

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.service.ts
> +        checkOut: checkOut.toJSON()
Do you really need toString and to JSON here?

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/ngx-bootstrap/datepicker/bs-datepicker.css">
Why do you need direct reference here? Isn't the css included in npm package you have imported?

2021-03-17 08:09 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
Wow! But why?
Why don't you filter those records in database?

2021-03-17 10:07 UTC, MaskaSaw commented on hotels-client-frontend/src/index.html
> +  <link rel="stylesheet" href="https://unpkg.com/ngx-bootstrap/datepicker/bs-datepicker.css">
I don't know why, but without this direct reference my custom datepicker doesn't look like it should.

2021-03-17 10:19 UTC, MaskaSaw commented on hotels-client-frontend/src/app/hotels/hotels.service.ts
> +        checkOut: checkOut.toJSON()
For dates it is required to have toJSON(), because without it they converts wrong in uri

2021-03-17 10:39 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
I tried a lot, but i just don't understand how to write such a huge correctly working LINQ expression. None of my variants worked.

2021-03-17 10:40 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    .ToList();
Without it all expression is invalid, because hotels already has type List<Hotel>

2021-03-17 10:46 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    .ToList();
Because hotels variable has List<Hotel> type already

2021-03-17 10:47 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +            }
Because i don't understand how to write such LINQ expression. Spent a lot of time trying, got no result.

2021-03-17 12:43 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.ts
> +    return false;
Can you simplify this? Why do you need several returns?

2021-03-18 11:05 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    );
Not sure about logic here...
What if there were no reservations at all?
What if there is a reservation that satisfies reservation.StartDate > inputParams.CheckOut condition, but there is another reservation that overlaps with the requested time interval?

2021-03-18 11:05 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +        public async Task<ActionResult<IEnumerable<Hotel>>> GetHotels([FromQuery]int page, int itemsPerPage,[FromQuery] HotelsParams inputParams)
Space after ,
Also line is probably too long

2021-03-18 11:57 UTC, andrei-kruhliakou-itechart approved these changes

2021-03-18 11:57 UTC, merged