Authentication
MaskaSaw/Hotels-project pull request #2
Opened 2021-02-09 11:15 UTC by MaskaSaw

Implemented JWT authentication and authorization, modified user registration mechanizm, added AuthController and AuthRepository.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart requested changes

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +    public class AuthRepository
Why this class has 'repository' in its name? What is repository exactly?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +        public AuthRepository(HotelsDBContext context)
Empty line

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +        public async Task<User> Login(string login, string password)
Empty line

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +                return null;
Always use code blocks with if (curly brackets) even if there is only one line of code.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +                return null;
Always use code blocks with if (curly brackets) even if there is only one line of code.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +                    if (computedHash[i] != passwordHash[i]) return false;
Always use code blocks with if (curly brackets) even if there is only one line of code.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +                for (int i = 0; i < computedHash.Length; i++)
Are there any alternatives to byte for byte comparison?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +                return true;
Always use code blocks with if (curly brackets) even if there is only one line of code.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +            var key = Encoding.ASCII.GetBytes(_config.GetSection("AppSettings:Token").Value);
Why the setting name 'Token'? Is it really token there?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +                }),
```suggestion
                Subject = new ClaimsIdentity(
                    new Claim[]
                    {
                        new Claim(ClaimTypes.NameIdentifier, userFromRepo.Id.ToString()),
                        new Claim(ClaimTypes.Name, userFromRepo.Login),
                        new Claim(ClaimTypes.Role, userFromRepo.Role)
                    }
                ),
```

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +            if (authUserId == reservation.UserId || authUserRole == "Admin")
There are like 10 places where you're using the same 4 lines of code. Is that a good practice? How can you improve that? 
Hint: consider writing extension method.

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +                .Value;
What if there are no claims of type 'Role'?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +                .Value;
You have exactly the same methods defined in other controllers. Why not reuse them?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +            });
```suggestion
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options => 
                    {
                        options.TokenValidationParameters = 
                             new TokenValidationParameters
                             {
                                 ValidateIssuerSigningKey = true,
                                 IssuerSigningKey = new SymmetricSecurityKey(key),
                                 ValidateIssuer = false,
                                 ValidateAudience = false
                             };
                    }
                );
```

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/HotelsDB/dbo/Tables/Users.sql
> +    [PasswordSalt] VARBINARY (MAX) NULL,
Is MAX really required here? What is the length of those fields?

2021-02-09 14:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            var auth = new AuthRepository(_context);
Why are you creating this instance? Shouldn't you use DI?

2021-02-10 07:49 UTC, MaskaSaw commented on hotels-backend/Hotels/Authentication/AuthRepository.cs
> +    public class AuthRepository
Because this construction is based on Repository Design Pattern, and this class acts as a middle layer between AuthController, UsersController and data access logic.

2021-02-10 09:08 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +                .Value;
If out JWT has no 'Role' field in it, it will be filtered by [Authorize] filter even before entering any methods that require user to be authorized.

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart requested changes

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Extensions/ControllerExtension.cs
> +        public static (int authUserId, string authUserRole) GetIdentity(this ControllerBase controller)
Is it a good name for method, does it really returns identity? 
Also why are you extending Controller class?

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +        public async Task<ActionResult<User>> PostUser(UserDTO userDTO,[FromServices] AuthRepository auth)
Why using method injection and not constructor?

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Authentication/HashGenerator.cs
> +        public static (byte[] passwordHash, byte[] passwordSalt) CreatePasswordHash(string password)
What is the benefit from introducing static class with only one simple method that is used only in one place?

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
>                  .ToListAsync();
```suggestion
                return await _context.Reservations
                    .Where(reservation => reservation.UserId == id)
                    .ToListAsync();
```

2021-02-10 10:13 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +            if (!ModelState.IsValid)
Use code block

2021-02-10 12:24 UTC, andrei-kruhliakou-itechart requested changes

2021-02-10 12:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +        private readonly AuthService _repo;
Is '_repo' suitable name for this field?

2021-02-10 12:24 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Extensions/IdentityExtension.cs
> +                .Value);
```suggestion
            return Convert.ToInt32(
                identity.Claims
                    .Where(x => x.Type == ClaimTypes.NameIdentifier)
                    .FirstOrDefault()
                    .Value
            );
```

2021-02-10 12:41 UTC, andrei-kruhliakou-itechart requested changes

2021-02-10 12:41 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +        private readonly AuthService __authService;
Why TWO underscores? :)

2021-02-10 12:41 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Extensions/IdentityExtension.cs
> +                    .Value);
```suggestion
            return Convert.ToInt32(
                identity.Claims
                    .Where(x => x.Type == ClaimTypes.NameIdentifier)
                    .FirstOrDefault()
                    .Value
            );
```

In such way you should clearly see where corresponding method call ends;

2021-02-10 12:43 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/AuthController.cs
> +        private readonly AuthService __authService;
Missclick

2021-02-10 16:33 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-10 16:33 UTC, merged