Reservation refactoring
MaskaSaw/Hotels-project pull request #23
Opened 2021-03-25 12:51 UTC by MaskaSaw

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart requested changes

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +             return await _context.Hotels
Indent

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +    [Authorize(Roles = "Admin")]
Indent

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation/reservation.component.ts
>    }
What is this?

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation/reservations.service.ts
> +  }
Why do you need to store this in local storage?

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/room/room.component.html
> +				</ul>
8 characters indent is really too much

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/room/room.component.ts
> +    let dates = JSON.parse(localStorage.getItem('dates')!);
why let?

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/room/room.component.ts
> +        let newService = new ReservationService();
why let?

2021-03-25 13:57 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.component.ts
> +        let newService = new ReservationService();
Why let?

2021-03-25 14:16 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/room/room.component.html
> +				</ul>
This is still an issue

2021-03-25 17:50 UTC, andrei-kruhliakou-itechart requested changes
Please review remaining issues.

2021-03-25 18:57 UTC, MaskaSaw commented on hotels-client-frontend/src/app/room/room.component.html
> +				</ul>
i dont know why, but on my PC there are 4 indents. Maybe some kind of github trouble?

2021-03-26 07:24 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation/reservations.service.ts
> +  }
Why are you continue to resolve this instead of answering the question?

2021-03-26 07:25 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/room/room.component.html
> +				</ul>
This usually means that you have tabs instead of spaces which should be avoided.

2021-03-26 08:20 UTC, MaskaSaw commented on hotels-client-frontend/src/app/reservation/reservations.service.ts
> +  }
Sorry, i've already deleted this part of code for previous review, just missed to save this file.

2021-03-26 08:24 UTC, MaskaSaw commented on hotels-client-frontend/src/app/room/room.component.html
> +				</ul>
Changed tabs to spaces, now should be ok.

2021-03-26 09:10 UTC, andrei-kruhliakou-itechart approved these changes

2021-03-26 09:10 UTC, merged