User reservation data display implemented
MaskaSaw/Hotels-project pull request #24
Opened 2021-03-26 14:56 UTC by MaskaSaw

2021-03-26 18:02 UTC, andrei-kruhliakou-itechart requested changes

2021-03-26 18:02 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +            var hotels = await _context.Hotels
Querying logic in this method should be simplified. You should be able to get all information with only one query starting from Reservation.

2021-03-26 18:02 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/authentication/auth.service.ts
> +
Why did you add empty line here?

2021-03-26 18:02 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/styles.less
> +
Unnecessary empty line

2021-03-29 12:29 UTC, andrei-kruhliakou-itechart requested changes

2021-03-29 12:29 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/UsersController.cs
> +                    })
You can avoid these joins if you use navigation properties on Reservation entity instead.

2021-03-29 17:46 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                    );
Unnecessary indent

2021-03-29 17:46 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
Why do you need this?

2021-03-29 19:57 UTC, MaskaSaw commented on hotels-backend/Hotels/Startup.cs
> +                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
Without it i get looping error while quering hotels from database

2021-03-30 07:37 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
And how exactly is JSON serializer related to database queries?

2021-03-30 12:15 UTC, andrei-kruhliakou-itechart requested changes

2021-03-30 12:15 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    })
```suggestion
                .Select(hotel => 
                    new HotelDTO
                    {
                        Id = hotel.Id,
                        Name = hotel.Name,
                        Country = hotel.Country,
                        City = hotel.City,
                        Address = hotel.Address,
                        Image = hotel.Image,
                        Services = hotel.Services,
                        RoomCount = hotel.Rooms.Count
                    }
                )
```
When creating new objects using multiline object initializer inside lambdas or method calls it is preferable to place new operator on a new line and indent {} accordingly so you can clearly see what belongs to object constructor.

For multiline method calls placing closing parenthesis on a new line can again clearly show you the boundaries of this method call.

2021-03-30 12:24 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                    })
Understood

2021-03-30 12:46 UTC, andrei-kruhliakou-itechart approved these changes

2021-03-30 12:46 UTC, merged