Search field reworked
MaskaSaw/Hotels-project pull request #27
Opened 2021-04-06 08:31 UTC by MaskaSaw

2021-04-06 10:14 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
Why do you need ToLocalTime() call here?

2021-04-06 10:34 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
Date format on client and server has GMT+3 , and because of Date to Json string format conversion on Angular, data from client and admin app has 3 hours difference with server. To restore it original value, ToLocalTime() was used.

2021-04-06 10:37 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
What if I call your API not from Angular but from some other client?

2021-04-06 10:41 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
While it has UTC format encoding, it will be good with it. Else, there can be problems.

2021-04-06 10:43 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
Then why do you expect UTC here if everything else is in the local time according to the above comment?

2021-04-06 10:53 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/RoomsController.cs
> +            block.End = block.End.ToLocalTime();
No, everything else is exactly in UTC, the only problem was with this exact method. This is the only place where we use and save time and date at the same place, so it needs a correction while saving it to DB.

2021-04-06 12:30 UTC, andrei-kruhliakou-itechart requested changes

2021-04-06 12:30 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/HotelsController.cs
> +                                block.End > DateTime.Now.ToUniversalTime()
You can use UtcNow property instead.

2021-04-07 09:06 UTC, andrei-kruhliakou-itechart approved these changes

2021-04-07 09:06 UTC, merged