SignalR logic implemented
MaskaSaw/Hotels-project pull request #29
Opened 2021-04-09 13:50 UTC by MaskaSaw

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart requested changes

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +                    .Include(createdReservation => createdReservation.User)
Why did you add those?

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/HubConfig/SignalHub.cs
> +    public class SignalHub: Hub
Can you think of a better name?

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.ts
> +    console.log('point hotel');
Do not leave debug info in your code

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.ts
> +    let index = this.hotels.findIndex(hotel => hotel.id === id);
Why let?

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/signal-r.service.ts
> +export class SignalRService {
Can you think of a better name here? SignalR is a technology, so it's like naming e.g. AngularService. This might make sense for a generic service that can do any operation (e.g. HttpService), but your service has specific purpose (sending/receiving reservation notifications).

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/signal-r.service.ts
> +      console.log(data);
Remove debug info

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.html
> +            <p *ngIf=reserved[i]>Someone just reserved room here!</p>
Indent

2021-04-09 15:40 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/HubConfig/SignalHub.cs
> +using System.Threading.Tasks;
Do you need all those namespaces?

2021-04-12 08:28 UTC, MaskaSaw commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +                    .Include(createdReservation => createdReservation.User)
Without this includes, createdReservation object had null values on Room and Room.Hotel fields, which are required for creation of new instance of ReservationDTO object.

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart requested changes

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                        .WithOrigins("http://localhost:4200")
This should be placed in config, how are you going to deploy this in production

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation-data-signal.service.ts
> +  private _dataObservable = new BehaviorSubject(new ReservationCreatedData());
Why the difference in naming? One has underscore prefix and the other doesn't.

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation-data-signal.service.ts
> +      .withUrl('https://localhost:44336/reservationData')
This should be in config as well

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Controllers/ReservationsController.cs
> +        public ReservationsController(HotelsDBContext context, IHubContext<SignalHub> hub)
You've renamed this, right? Does it even compile?

2021-04-12 09:21 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/reservation-data-signal.service.ts
> +        .then(() => console.log('connection started'))
Do not leave debug info

2021-04-12 13:22 UTC, andrei-kruhliakou-itechart approved these changes

2021-04-12 13:23 UTC, merged