Admin components
MaskaSaw/Hotels-project pull request #3
Opened 2021-02-12 13:09 UTC by MaskaSaw

Created Login, Hotels, Rooms, Users and Reservations components, configured routings for these components. Created Hotel, Room, User and Reservation models. Configured user authentication and JWT-token saving.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart requested changes

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/app.module.ts
> +
Why empty line here? Next import is logically belongs to the above group.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/auth.service.spec.ts
> +import { TestBed } from '@angular/core/testing';
Please disable test files generation unless you planning to actually write and run them.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/auth.service.ts
> +  private loginUrl = 'https://localhost:44336/api/auth/Login';
Please move host (or base url) to some configuration file. Check what is the Angular way of doing this.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/auth.service.ts
> +    })
```suggestion
    this.http.post<User>(this.loginUrl, user, this.httpOptions)
      .subscribe((resp: any) => {
        this.router.navigate(['/hotels']);
        localStorage.setItem('auth_token', resp.tokenString);
      });
```

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/auth.service.ts
> +    })
Be consistent: either use semicolon at the end of each statement (preferred) or don't.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/auth.service.ts
> +  public get logIn(): boolean {
Is it a good name for property? How is it different from the method above?

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +    { id: 0, name: "TestName", country: "TestCountry", city: "TestCity", address: "TestAddress", parking: true, massage: false, extraTowels: true, image: "No content"}]
This line is too long and its hard to read it, especially online (e.g. on GitHub). Please do not exceed 120 characters limit for a single line.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +    { id: 0, name: "TestName", country: "TestCountry", city: "TestCity", address: "TestAddress", parking: true, massage: false, extraTowels: true, image: "No content"}]
You already have required API on backend, why using dummy data?

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +import { Router } from '@angular/router';
Group imports logically. Separate imports from your own code from third-party code.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/login/login.component.html
> +<div *ngIf='authService.logIn'>
Use double quotes in html.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/login/login.component.html
> +      <button  type='submit' (click)='Login()'>Login</button>
Unnecessary space after 'button'

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations.service.ts
> +    localStorage.setItem('reservations', JSON.stringify(this.reservations));
Why are you saving reservations in local storage?

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.component.ts
> +    //{ id: 0, roomId: 0, userId: 0, startDate: new Date(), endDate: new Date(), arrivalTime: new Date(), parking: true, massage: false, extraTowels: true}
Do not leave commented out code.

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +    { id: 0, hotelId: 0, roomNumber: '0A', roomType: 'Standart', vacantBeds: 4, cost: 50.00, reserved: false, available: true, image: '', reservations: []}
Why do you need dummy data?

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                c.AddPolicy("AllowOrigin", options => options.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
Is it a good name for policy?

2021-02-12 14:50 UTC, andrei-kruhliakou-itechart commented on hotels-backend/Hotels/Startup.cs
> +                c.AddPolicy("AllowOrigin", options => options.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
```suggestion
                c.AddPolicy(
                    "AllowOrigin", 
                    options => options
                        .AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                );
```

2021-02-15 08:56 UTC, MaskaSaw commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +    { id: 0, name: "TestName", country: "TestCountry", city: "TestCity", address: "TestAddress", parking: true, massage: false, extraTowels: true, image: "No content"}]
I use dummy data, because I plan to setup data loading and initialization of components together with the creation of services, that will receive this data from the server, in the next task.

2021-02-15 09:10 UTC, MaskaSaw commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +    { id: 0, hotelId: 0, roomNumber: '0A', roomType: 'Standart', vacantBeds: 4, cost: 50.00, reserved: false, available: true, image: '', reservations: []}
I use dummy data, because I plan to setup data loading and initialization of components together with the creation of services, that will receive this data from the server, in the next task.

2021-02-15 13:45 UTC, andrei-kruhliakou-itechart requested changes

2021-02-15 13:45 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations.service.ts
> +    //localStorage.setItem('reservations', JSON.stringify(this.reservations));
Please do not leave commented out code

2021-02-15 13:45 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.component.ts
> +    }
You are calling getReservations() 2 times. What if this call actually requires roundtrip to backend and database? Is it a good idea?

2021-02-15 13:45 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.component.ts
> +import {Subscription} from 'rxjs';
Spaces around Subscription, be consistent with code style.

2021-02-15 13:46 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +    { id: 0, hotelId: 0, roomNumber: '0A', roomType: 'Standart', vacantBeds: 4, cost: 50.00, reserved: false, available: true, image: '', reservations: []}
Either do not commit it to the repo or at least leave some todo comment.

2021-02-16 07:55 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-16 07:55 UTC, merged