Client redesign
MaskaSaw/Hotels-project pull request #30
Opened 2021-04-15 10:21 UTC by MaskaSaw

2021-04-15 10:50 UTC, andrei-kruhliakou-itechart requested changes

2021-04-15 10:50 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/authentication/authentication.component.less
> +	min-width: 100px;
Indents

2021-04-15 10:50 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/authentication/authentication.component.less
> +	  	margin-left: 35%;
Indents

2021-04-15 10:50 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/authentication/authentication.component.less
> +	  	margin-left: 42%;
Indents

2021-04-15 10:50 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.less
> +  display: block !important;
Avoid using !implortant unless absolutely necessary

2021-04-15 11:10 UTC, MaskaSaw commented on hotels-client-frontend/src/app/hotels/hotels.component.less
> +  display: block !important;
Yeah, could not find another solution and used it like a last chance here

2021-04-15 12:25 UTC, andrei-kruhliakou-itechart commented on hotels-client-frontend/src/app/hotels/hotels.component.less
> +  display: block !important;
And what exactly is the problem here?

2021-04-15 18:38 UTC, MaskaSaw commented on hotels-client-frontend/src/app/hotels/hotels.component.less
> +  display: block !important;
Inline styles of datepicker are always used before any class parameters from my .less files, and i need to change it's display style to block for right positioning on low-width screens

2021-04-16 07:43 UTC, andrei-kruhliakou-itechart approved these changes

2021-04-16 07:43 UTC, merged