Data uploading
MaskaSaw/Hotels-project pull request #6
Opened 2021-02-18 14:17 UTC by MaskaSaw

New entities uploading to the server from admins app.

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart requested changes

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/hotels/hotels.component.ts
> +   }
Indentation

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/mock-objects.ts
> +import { Hotel } from './hotel';
Not sure why are you still using mocks?

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.component.ts
>        if (this.route.toString().includes('rooms')) {
Can you think of a more elegant and fool-proof solution instead of just searching the whole route for substring?
Just a thought, not a required change right now.

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.service.ts
> +    );
Indentation

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/reservations/reservations.service.ts
> +    let url = this.setUrl(id, type);
Why let? Are changing it somewhere?

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.component.ts
> +          this.rooms.push(room)
Semicolon

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/rooms/rooms.service.ts
> +    );
Indentation

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/users/users.service.ts
> +    );
Indentation

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +}
Use the power of less - nested selectors, e.g.
.add-form {
  ...

  h2 {
    ...
  }

  ul {
    ...
  }
}

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +.add-form textarea {padding:8px; width:300px;}
Don't write styles like this, use proper formatting

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +    border-color: rgb(51, 122, 183);
Use the power of less - define some variables for colors and reuse them across application

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +*:focus {outline: none;}
formatting

2021-02-18 18:19 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +}
Use selector nesting

2021-02-19 07:47 UTC, MaskaSaw commented on hotels-admin-frontend/src/app/mock-objects.ts
> +import { Hotel } from './hotel';
This file stores constants for zeroing the objects with which the input fields are binded.

2021-02-19 09:13 UTC, andrei-kruhliakou-itechart requested changes

2021-02-19 09:13 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/styles.less
> +    }
You can nest :hover inside button

2021-02-19 09:13 UTC, andrei-kruhliakou-itechart commented on hotels-admin-frontend/src/app/mock-objects.ts
> +import { Hotel } from './hotel';
Then you got wrong name here. Mock is something that substitute real object mostly for testing purposes.

2021-02-19 09:44 UTC, andrei-kruhliakou-itechart approved these changes

2021-02-19 09:45 UTC, merged